// <auto-generated />
using System;
using BlogApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogApi.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20250513051016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogApi.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is my first post in the blog",
                            CreateAt = new DateTime(2025, 5, 13, 8, 10, 14, 484, DateTimeKind.Local).AddTicks(9294),
                            Title = "The first post in the blog"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is my second post in the blog",
                            CreateAt = new DateTime(2025, 5, 13, 8, 10, 14, 486, DateTimeKind.Local).AddTicks(3585),
                            Title = "The second post in the blog"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is my third post in the blog",
                            CreateAt = new DateTime(2025, 5, 13, 8, 10, 14, 486, DateTimeKind.Local).AddTicks(3597),
                            Title = "The third post in the blog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
